// JavaScript source code
// PRODUCTOS REALES PARA SPORT & FITNESS
const productos = [
    {
        id: 1,
        nombre: "Colchoneta Deportiva 100 x 50 x 5 cm | ",
        precio: 16990,
        precioOriginal: 19990,
        categoria: "Otros",
        imagen: "🥛",
        descripcion: "La Colchoneta Deportiva 100 x 50 x 5 cm (Densidad 80 PVC) es perfecta para entrenamientos en casa, gimnasios, escuelas y centros deportivos. Fabricada en PVC de alta resistencia, ofrece firmeza y durabilidad, al mismo tiempo que proporciona una superficie cómoda y segura para realizar distintos tipos de ejercicios.Su densidad 80 la hace ideal para entrenamientos de fuerza, pilates, yoga, artes marciales y rehabilitación, brindando soporte y absorción de impactos en cada movimiento.Compacta y versátil, se adapta a rutinas individuales y grupales, permitiendo entrenar con confianza y comodidad.",
        marca: "NA",
        stock: 15,
        destacado: true,
        descuento: 15
    },
    {
        id: 2,
        nombre: "Creatina Monohidrato 300g",
        precio: 18990,
        precioOriginal: 21990,
        categoria: "proteina",
        imagen: "💊",
        descripcion: "Creatina pura en polvo, aumenta fuerza y masa muscular. 100% monohidrato.",
        marca: "MyProtein",
        stock: 25,
        destacado: true,
        descuento: 10
    },
    {
        id: 3,
        nombre: "BCAA 2:1:1 400g",
        precio: 22990,
        precioOriginal: 25990,
        categoria: "proteina",
        imagen: "💪",
        descripcion: "Aminoácidos ramificados, sabor frutos tropicales. Recuperación muscular.",
        marca: "BSN",
        stock: 18,
        destacado: false,
        descuento: 12
    },
    {
        id: 4,
        nombre: "Set Mancuernas Ajustables 20kg",
        precio: 89990,
        precioOriginal: 99990,
        categoria: "equipo",
        imagen: "🏋️",
        descripcion: "Set de mancuernas ajustables de 2x10kg. Incluye barra y discos.",
        marca: "ProFitness",
        stock: 8,
        destacado: true,
        descuento: 10
    },
    {
        id: 5,
        nombre: "Colchoneta Yoga Premium 10mm",
        precio: 24990,
        precioOriginal: 27990,
        categoria: "equipo",
        imagen: "🧘",
        descripcion: "Colchoneta antideslizante extra gruesa. Ideal para yoga y pilates.",
        marca: "Liforme",
        stock: 30,
        destacado: false,
        descuento: 8
    },
    {
        id: 6,
        nombre: "Bandas de Resistencia Set 5",
        precio: 15990,
        precioOriginal: 17990,
        categoria: "equipo",
        imagen: "🎗️",
        descripcion: "Set de 5 bandas elásticas con diferentes niveles de resistencia.",
        marca: "TheraBand",
        stock: 40,
        destacado: true,
        descuento: 12
    },
    {
        id: 7,
        nombre: "Camiseta Dry-Fit Deportiva",
        precio: 19990,
        precioOriginal: 22990,
        categoria: "ropa",
        imagen: "👕",
        descripcion: "Camiseta técnica transpirable. Tecnología dry-fit. Varios colores.",
        marca: "Nike",
        stock: 50,
        destacado: false,
        descuento: 15
    },
    {
        id: 8,
        nombre: "Shorts Deportivos Compresión",
        precio: 17990,
        precioOriginal: 19990,
        categoria: "ropa",
        imagen: "🩳",
        descripcion: "Shorts de compresión para entrenamiento. Soporte muscular.",
        marca: "Under Armour",
        stock: 35,
        destacado: true,
        descuento: 10
    },
    {
        id: 9,
        nombre: "Zapatillas Cross Training",
        precio: 79990,
        precioOriginal: 89990,
        categoria: "ropa",
        imagen: "👟",
        descripcion: "Zapatillas multipropósito para crossfit y entrenamiento funcional.",
        marca: "Reebok",
        stock: 12,
        destacado: true,
        descuento: 12
    },
    {
        id: 10,
        nombre: "Glutamina Recovery 500g",
        precio: 16990,
        precioOriginal: 18990,
        categoria: "proteina",
        imagen: "🔬",
        descripcion: "Glutamina en polvo para recuperación muscular y sistema inmune.",
        marca: "Dymatize",
        stock: 22,
        destacado: false,
        descuento: 8
    },
    {
        id: 11,
        nombre: "Barra Proteínas 12 unidades",
        precio: 12990,
        precioOriginal: 14990,
        categoria: "proteina",
        imagen: "🍫",
        descripcion: "Barritas proteicas sabor chocolate. 20g de proteína por barra.",
        marca: "Quest Nutrition",
        stock: 60,
        destacado: true,
        descuento: 15
    },
    {
        id: 12,
        nombre: "Rodillo Masaje Muscular",
        precio: 13990,
        precioOriginal: 15990,
        categoria: "equipo",
        imagen: "🎯",
        descripcion: "Rodillo de foam para liberación miofascial y recuperación.",
        marca: "TriggerPoint",
        stock: 28,
        destacado: false,
        descuento: 14
    },
    {
        id: 13,
        nombre: "Botella Shaker 700ml",
        precio: 7990,
        precioOriginal: 8990,
        categoria: "accesorios",
        imagen: "🥤",
        descripcion: "Shaker profesional para batidos de proteína. Incluye bola mezcladora.",
        marca: "BlenderBottle",
        stock: 100,
        destacado: true,
        descuento: 12
    },
    {
        id: 14,
        nombre: "Pre-Entreno Explosive 300g",
        precio: 29990,
        precioOriginal: 34990,
        categoria: "proteina",
        imagen: "⚡",
        descripcion: "Pre-entrenamiento con cafeína y beta-alanina. Energía y enfoque.",
        marca: "C4 Sport",
        stock: 20,
        destacado: true,
        descuento: 15
    },
    {
        id: 15,
        nombre: "Cinta Correr Plegable",
        precio: 299990,
        precioOriginal: 349990,
        categoria: "equipo",
        imagen: "🏃",
        descripcion: "Cinta de correr motorizada plegable. 12 programas predefinidos.",
        marca: "ProForm",
        stock: 5,
        destacado: true,
        descuento: 15
    },
    {
        id: 16,
        nombre: "Set Pesas Rusas 8-16kg",
        precio: 129990,
        precioOriginal: 149990,
        categoria: "equipo",
        imagen: "⚖️",
        descripcion: "Set de 3 kettlebells (8kg, 12kg, 16kg). Ideal para entrenamiento funcional.",
        marca: "Rogue",
        stock: 6,
        destacado: false,
        descuento: 14
    },
    {
        id: 17,
        nombre: "Leggings Deportivos Mujer",
        precio: 22990,
        precioOriginal: 25990,
        categoria: "ropa",
        imagen: "🧦",
        descripcion: "Leggings de alta compresión. Tiro alto y tejido transpirable.",
        marca: "Gymshark",
        stock: 45,
        destacado: true,
        descuento: 12
    },
    {
        id: 18,
        nombre: "Multivitamínico Completo",
        precio: 14990,
        precioOriginal: 16990,
        categoria: "proteina",
        imagen: "🌿",
        descripcion: "Multivitamínico con minerales esenciales. Apoyo nutricional completo.",
        marca: "Animal Pak",
        stock: 35,
        destacado: false,
        descuento: 12
    },
    {
        id: 19,
        nombre: "Cuerda Saltar Profesional",
        precio: 8990,
        precioOriginal: 9990,
        categoria: "equipo",
        imagen: "🔄",
        descripcion: "Cuerda para saltar ajustable con rodamientos de bolas. Contador incluido.",
        marca: "CrossFit",
        stock: 65,
        destacado: true,
        descuento: 11
    },
    {
        id: 20,
        nombre: "Chaleco Lastrado 20kg",
        precio: 45990,
        precioOriginal: 49990,
        categoria: "equipo",
        imagen: "🦺",
        descripcion: "Chaleco lastrado ajustable. Ideal para calistenia y running.",
        marca: "ZFO Sports",
        stock: 10,
        destacado: false,
        descuento: 9
    }
];